### ISSUE TITLE
[WFRP4e System] Some actors and items throw errors when migrating to v11 exclusive

### ISSUE THREAD

**Issue by moo-man** [moo-man/WFRP4e-FoundryVTT#1752]
Yellow Fang Spy and Wuder Lechart actors throw errors saying "Error replacing links: Type error: html.replaceAll is not a function", the same happens for some skills, and other various items. there is a whole total of 105 of them<br/>**From**: Perkuns#9523<br/>foundry: 11.308<br/>wfrp4e: 7.0.1<br/>wfrp4e-altdorf: 4.0.0<br/>wfrp4e-archives1: 4.0.0<br/>wfrp4e-archives2: 4.0.0<br/>wfrp4e-core: 4.0.0<br/>wfrp4e-dotr: 4.0.0<br/>wfrp4e-eis: 4.0.0<br/>wfrp4e-empire-ruins: 4.0.0<br/>wfrp4e-horned-rat: 4.0.0<br/>wfrp4e-middenheim: 4.0.0<br/>wfrp4e-owb1: 4.0.0<br/>wfrp4e-pbtt: 4.0.0<br/>wfrp4e-rnhd: 4.0.0<br/>wfrp4e-starter-set: 4.0.0<br/>wfrp4e-ua1: 4.0.0<br/>wfrp4e-ua2: 4.0.0<br/>wfrp4e-up-in-arms: 4.0.0<br/>wfrp4e-wom: 4.0.0<br/>Active Modules: about-time, acelib, ATL, breaktime, colorsettings, custom-css, dice-calculator, dice-so-nice, drag-ruler, easy-target, find-the-culprit, forien-armoury, forien-copy-environment, forien-quest-log, foundryvtt-simple-calendar, fuzzy-foundry, gm-token-drag-visibility-v2, image-hover, item-piles, lib-captions, lib-changelogs, lib-find-the-path, lib-wrapper, module-credits, monks-scene-navigation, party-overview, permission_viewer, popout, quick-insert, remote-highlight-ui, routinglib, silence-compatibility-warnings, socketlib, sweetnothings, times-up, token-action-hud, token-auras, vtta-tokenizer, wall-height, wfrp4e-dotr-maps, wfrp4e-eis-maps, wfrp4e-ubersreik-maps, _CodeMirror

**Comment by SimonasBanys** [comment]
![image](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/31985858/7e2dbbfd-c479-4835-aaa9-21c389895d31)
![image](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/31985858/e94504c8-d659-4425-ab73-5d1128ae1a7b)
![image](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/31985858/33f42aaf-1a59-4499-98f5-ca0c1978a478)
![image](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/31985858/21a443ea-107a-4a7d-bc12-e25a4d565813)
![image](https://github.com/moo-man/WFRP4e-FoundryVTT/assets/31985858/fc6db6cc-799b-46bd-a648-16c6a6f97a3e)
 those (most) of what I could find and which objects, I suspect the ones following actors could be due to failure with actor itself, but some seem to be just for skills or equipment just on their own

**Comment by moo-man** [comment]
I remember using your test world and many of your skill descriptions were blank, this is probably the cause.
